site_name: jwt-auth
pages:
    - Home: index.md
    - Laravel Installation: laravel-installation.md
    - Lumen Installation (incomplete): lumen-installation.md
    - Quick start: quick-start.md
    - Auth guard: auth-guard.md
    - Configuration: configuration.md
    - Exception Handling: exception-handling.md
    - Resources: resources.md
theme: readthedocs
